services:
  extractor-ui:
    build:
      context: ..
      dockerfile: docker/Dockerfile.web
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./ssl:/etc/nginx/ssl:ro
    restart: unless-stopped

  playwright-extractor:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "3050:3050"
    restart: unless-stopped

  # ollama:
  #   image: ollama/ollama:0.3.14
  #   ports:
  #     - "11434:11434"
  #   environment:
  #     - OLLAMA_HOST=0.0.0.0
  #     - OLLAMA_ORIGINS=file://,https://localhost:8443,https://127.0.0.1:8443
  #   volumes:
  #     - ollama-data:/root/.ollama
  #   restart: unless-stopped
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - capabilities: [gpu]
  #             count: all
  #             driver: nvidia
  #             optional: true

# volumes:
#   ollama-data:
